# Generated by Django 5.2.5 on 2025-09-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="grade",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
