# Generated by Django 5.2.5 on 2025-09-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0002_alter_testresult_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='grade',
            field=models.CharField(max_length=15, blank=True),
        ),
    ]
