# Generated by Django 5.2.5 on 2025-09-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0003_auto_20250924_1248"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testattempt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="attempt_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="is_retake",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TestRetakeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(help_text="Qayta ishlash sababi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, help_text="Admin javobi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_retakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retake_requests",
                        to="tests_app.testattempt",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retake_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retake_requests",
                        to="tests_app.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("student", "test", "previous_attempt")},
            },
        ),
    ]
