# Generated by Django 5.2.5 on 2025-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0004_alter_testattempt_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testretakerequest",
            name="is_used",
            field=models.BooleanField(
                default=False, help_text="Qayta ishlash so'rovi ishlatilganmi"
            ),
        ),
    ]
